---
title: "Day 5, Loops Review & DplyR"
author: "Analise Hofmann"
date: "March 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Review 1

```{r}
#read in the table from Day 03
#practice changing working directories
day3table <- read.csv(file = "./Day_03_WorkAlong/TestData.csv")



```


## Review 2

```{r}
#use the table you read in above and write a for loop to modify it
day3table_original <- day3table
for(i in 1:3){ 
  #day3table[ 1, i ]<- 
  print (c(" column i is : ", i))  
  print(paste("column i is: ", i, sep = ","))
  
  for ( j in 1:12){ 
    print(c("row j is: ", j))
      temp <- day3table[ j, i ] + 1 
     
      print (temp)
      day3table[ j, i ] <- temp
      
       }
  
}
```

## Connie's challenge to the group! 
Make a new column in day3table called "Sum" and sum the first three columns in each row, and put the sum into the new column
```{r}
day3table <- day3table_original #setting day3table back to original values

day3table[ ,"Sum"] <- NA # adding new empty column with NAs

#write a for loop to calculate the sum of each row and put it into our new column

for (i in 1:nrow(day3table)){
  
  temp <- sum(day3table[i, 1:3])
  # temp <- day3data[i,1] + day3data[i,2] + day3data[i,3] #Lucia's way
  
  # day3table[i, 4] <- temp # easiest way 
  day3table$Sum[i] <- temp #Lucia's way
  # day3table[i, "Sum"] <- temp #another alternate way
  
}






```

## New Material for Day 6
### Making a function

```{r}
# we have made a function called Sum3Columns

Sum3Column <- function(table, columns, nameOfColumn){
 #this function will sum the first 3 columns of a dataframe into a new column
   #table is a dataframe 
  #columns, is a list of numbers for the columns we want to sum
  #nameOfColumn is a string to name our new column
  
table[ ,nameOfColumn] <- NA  
  
  for (i in 1:nrow(table)){
  print(paste("Row i is:", i))
  temp <- sum(table[i, columns])
  # temp <- day3data[i,1] + day3data[i,2] + day3data[i,3] #Lucia's way
  
  # day3table[i, 4] <- temp # easiest way 
 # table$Sum[i] <- temp #Lucia's way
  table[i, nameOfColumn] <- temp #another alternate way
  
}
  
return(table)

}

day3table <- day3table_original
columsToSum <- 

#calling the function by its name and specifying specific values/variables for each argument
functionTable <- Sum3Column(day3table, 1:2 , "Sum")

```



